apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default
  destination:
    namespace: gitea
    name: in-cluster
  source:
    repoURL: 'https://dl.gitea.io/charts/'
    chart: gitea
    targetRevision: 5.0.3
    helm:
      releaseName: gitea
      values: |
        gitea:
          admin:
            #existingSecret: gitea-admin-secret
            username: superuser
            password: password
            email: "gitea@local.domain"

          metrics:
            enabled: false
            serviceMonitor:
              enabled: false

          config: {}
        postgresql:
          enabled: true
          global:
            postgresql:
              postgresqlDatabase: gitea
              postgresqlUsername: gitea
              postgresqlPassword: gitea
              servicePort: 5432
          persistence:
            size: 1Gi

        memcached:
          enabled: false
          service:
            port: 11211

        checkDeprecation: true
       
  syncPolicy:
    automated:
      prune: true
      selfHeal: true